### ISSUE TITLE
Error initializing AttributeResolver with Couchbase backend

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-oxshibboleth#7]
Full log from `idp-warn.log`:

```
2019-07-24 13:59:29,687 -  - WARN [net.shibboleth.utilities.java.support.net.CookieManager:171] - Use of secure property is strongly advised
2019-07-24 13:59:29,725 -  - WARN [net.shibboleth.utilities.java.support.net.CookieManager:171] - Use of secure property is strongly advised
2019-07-24 13:59:30,355 -  - WARN [DEPRECATED:118] - xsi:type '{urn:mace:shibboleth:2.0:resolver:dc}RelationalDatabase', (file [/opt/shibboleth-idp/conf/attribute-resolver.xml]): This will be removed in the next major version of this software; replacement is {urn:mace:shibboleth:2.0:resolver}RelationalDatabase
2019-07-24 13:59:31,654 -  - WARN [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:551] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteDataConnector': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
2019-07-24 13:59:31,658 -  - ERROR [net.shibboleth.utilities.java.support.service.AbstractReloadableService:182] - Service 'shibboleth.AttributeResolverService': Initial load failed
net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteDataConnector': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:377)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteDataConnector': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1631)
Caused by: java.lang.ExceptionInInitializerError: null
	at org.boon.json.JsonMappingParser.<init>(JsonMappingParser.java:85)
Caused by: java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
	at org.boon.core.reflection.FastStringUtils$StringImplementation$1.toCharArray(FastStringUtils.java:92)
2019-07-24 13:59:34,518 -  - WARN [net.shibboleth.ext.spring.context.DelimiterAwareApplicationContext:551] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.metrics.RegisterMetricSets$child#0' defined in URL [file:/opt/shibboleth-idp/conf/admin/metrics.xml]: Cannot resolve reference to bean 'shibboleth.metrics.AttributeResolverGaugeSet' while setting bean property 'arguments' with key [7]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.metrics.AttributeResolverGaugeSet' defined in URL [file:/opt/shibboleth-idp/system/conf/general-admin-system.xml]: Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Injected service was null or not an AttributeResolver
2019-07-24 13:59:34,618 -  - ERROR [org.springframework.web.context.ContextLoader:350] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.metrics.RegisterMetricSets$child#0' defined in URL [file:/opt/shibboleth-idp/conf/admin/metrics.xml]: Cannot resolve reference to bean 'shibboleth.metrics.AttributeResolverGaugeSet' while setting bean property 'arguments' with key [7]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.metrics.AttributeResolverGaugeSet' defined in URL [file:/opt/shibboleth-idp/system/conf/general-admin-system.xml]: Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Injected service was null or not an AttributeResolver
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.metrics.AttributeResolverGaugeSet' defined in URL [file:/opt/shibboleth-idp/system/conf/general-admin-system.xml]: Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Injected service was null or not an AttributeResolver
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1631)
Caused by: net.shibboleth.utilities.java.support.component.ComponentInitializationException: Injected service was null or not an AttributeResolver
	at net.shibboleth.idp.attribute.resolver.impl.AttributeResolverServiceGaugeSet.doInitialize(AttributeResolverServiceGaugeSet.java:104)
```

Environment:

```
Runtime: docker
OS: Alpine
JVM: AdoptOpenJDK 11.0.4_11
```

**Comment by iromli** [comment]
oxShibboleth working fine when running under Java 8.
It seems `boon` package doesn't support Java 11.
Switching back to Java 8 for now.

**Comment by iromli** [comment]
Any thought about this issue /cc @syntrydy ?

**Comment by iromli** [comment]
Closing this issue as we will stick to Java 8
